// <auto-generated />
using System;
using ISC.AI.Modules.DocFlow.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ISC.AI.Modules.DocFlow.Data.Migrations
{
    [DbContext(typeof(DocFlowDbContext))]
    [Migration("20260805105910_DocumentCore")]
    partial class DocumentCore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("docflow")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.AssignmentStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("integer")
                        .HasColumnName("assignment_id");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("changed_by_user_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("FromStatus")
                        .HasColumnType("integer")
                        .HasColumnName("from_status");

                    b.Property<int>("ToStatus")
                        .HasColumnType("integer")
                        .HasColumnName("to_status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_assignment_status_history");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("ix_assignment_status_history_assignment_id");

                    b.ToTable("assignment_status_history", "docflow");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.DeadlineExtension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("integer")
                        .HasColumnName("assignment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("InitiatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("initiated_by_user_id");

                    b.Property<DateOnly>("NewDeadline")
                        .HasColumnType("date")
                        .HasColumnName("new_deadline");

                    b.Property<DateOnly>("OldDeadline")
                        .HasColumnType("date")
                        .HasColumnName("old_deadline");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_deadline_extension");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("ix_deadline_extension_assignment_id");

                    b.ToTable("deadline_extension", "docflow");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.DeadlineExtensionFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ExtensionId")
                        .HasColumnType("integer")
                        .HasColumnName("extension_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("stored_file_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_deadline_extension_file");

                    b.HasIndex("ExtensionId")
                        .HasDatabaseName("ix_deadline_extension_file_extension_id");

                    b.ToTable("deadline_extension_file", "docflow");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AggregatedStatus")
                        .HasColumnType("integer")
                        .HasColumnName("aggregated_status");

                    b.Property<short>("Classification")
                        .HasColumnType("smallint")
                        .HasColumnName("classification");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DirectionFlag")
                        .HasColumnType("integer")
                        .HasColumnName("direction_flag");

                    b.Property<int>("DivisionId")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<string>("FullText")
                        .HasColumnType("text")
                        .HasColumnName("full_text");

                    b.Property<int?>("InspectorUserId")
                        .HasColumnType("integer")
                        .HasColumnName("inspector_user_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateOnly>("RegDate")
                        .HasColumnType("date")
                        .HasColumnName("reg_date");

                    b.Property<string>("RegNumber")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reg_number");

                    b.Property<int?>("RegisteredByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("registered_by_user_id");

                    b.Property<string>("ShortContent")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("short_content");

                    b.Property<string>("Source")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_document");

                    b.HasIndex("RegDate")
                        .HasDatabaseName("ix_document_reg_date");

                    b.HasIndex("RegNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_document_reg_number");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_document_type_id");

                    b.HasIndex("AggregatedStatus", "UpdatedAt")
                        .HasDatabaseName("ix_document_aggregated_status_updated_at");

                    b.HasIndex("DivisionId", "Classification")
                        .HasDatabaseName("ix_document_division_id_classification");

                    b.ToTable("document", "docflow", t =>
                        {
                            t.HasCheckConstraint("chk_document_aggregated_status", "aggregated_status IN (0, 1, 2, 3, 4, 5, 6)");

                            t.HasCheckConstraint("chk_document_direction_flag", "direction_flag IN (1, 2, 3)");

                            t.HasCheckConstraint("chk_document_priority", "priority IS NULL OR priority IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssigneeUserId")
                        .HasColumnType("integer")
                        .HasColumnName("assignee_user_id");

                    b.Property<int?>("ControllerUserId")
                        .HasColumnType("integer")
                        .HasColumnName("controller_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("Deadline")
                        .HasColumnType("date")
                        .HasColumnName("deadline");

                    b.Property<int>("DivisionId")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("UseCommonDeadline")
                        .HasColumnType("boolean")
                        .HasColumnName("use_common_deadline");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_document_assignment");

                    b.HasIndex("AssigneeUserId")
                        .HasDatabaseName("ix_document_assignment_assignee_user_id");

                    b.HasIndex("DivisionId")
                        .HasDatabaseName("ix_document_assignment_division_id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_document_assignment_document_id");

                    b.ToTable("document_assignment", "docflow", t =>
                        {
                            t.HasCheckConstraint("chk_assignment_status", "status IN (1, 2, 3, 4, 5, 6, 7)");
                        });
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("stored_file_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_document_attachment");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_document_attachment_document_id");

                    b.ToTable("document_attachment", "docflow");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("boolean")
                        .HasColumnName("is_latest");

                    b.Property<int>("Language")
                        .HasColumnType("integer")
                        .HasColumnName("language");

                    b.Property<string>("PdfCopyStoredFileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pdf_copy_stored_file_name");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("stored_file_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("uploaded_by_user_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_document_file");

                    b.HasIndex("DocumentId", "IsLatest")
                        .HasDatabaseName("ix_document_file_document_id_is_latest");

                    b.ToTable("document_file", "docflow");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Group")
                        .HasColumnType("integer")
                        .HasColumnName("group");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_document_type");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_document_type_name");

                    b.ToTable("document_type", "docflow", t =>
                        {
                            t.HasCheckConstraint("chk_document_type_group", "\"group\" IN (1, 2)");
                        });
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.StatusHistoryFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<int>("StatusHistoryId")
                        .HasColumnType("integer")
                        .HasColumnName("status_history_id");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("stored_file_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_status_history_file");

                    b.HasIndex("StatusHistoryId")
                        .HasDatabaseName("ix_status_history_file_status_history_id");

                    b.ToTable("status_history_file", "docflow");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.AssignmentStatusHistory", b =>
                {
                    b.HasOne("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentAssignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_status_history_document_assignments_assignment_id");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.DeadlineExtension", b =>
                {
                    b.HasOne("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentAssignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deadline_extension_document_assignments_assignment_id");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.DeadlineExtensionFile", b =>
                {
                    b.HasOne("ISC.AI.Modules.DocFlow.Domain.Entities.DeadlineExtension", null)
                        .WithMany()
                        .HasForeignKey("ExtensionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deadline_extension_file_deadline_extension_extension_id");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.Document", b =>
                {
                    b.HasOne("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_document_document_types_type_id");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentAssignment", b =>
                {
                    b.HasOne("ISC.AI.Modules.DocFlow.Domain.Entities.Document", "Document")
                        .WithMany("Assignments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_assignment_documents_document_id");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentAttachment", b =>
                {
                    b.HasOne("ISC.AI.Modules.DocFlow.Domain.Entities.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_attachment_documents_document_id");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentFile", b =>
                {
                    b.HasOne("ISC.AI.Modules.DocFlow.Domain.Entities.Document", null)
                        .WithMany("Files")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_file_document_document_id");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.StatusHistoryFile", b =>
                {
                    b.HasOne("ISC.AI.Modules.DocFlow.Domain.Entities.AssignmentStatusHistory", null)
                        .WithMany()
                        .HasForeignKey("StatusHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_status_history_file_assignment_status_history_status_histor");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.Document", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
