// <auto-generated />
using System;
using ISC.AI.Modules.DocFlow.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ISC.AI.Modules.DocFlow.Data.Migrations
{
    [DbContext(typeof(DocFlowDbContext))]
    [Migration("20260810052325_CommentFileVersion")]
    partial class CommentFileVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("docflow")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.AssignmentReassignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("integer")
                        .HasColumnName("assignment_id");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("changed_by_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("FromUserId")
                        .HasColumnType("integer")
                        .HasColumnName("from_user_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<int>("ToUserId")
                        .HasColumnType("integer")
                        .HasColumnName("to_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_assignment_reassignment");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("ix_assignment_reassignment_assignment_id");

                    b.ToTable("assignment_reassignment", "docflow");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.AssignmentStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("integer")
                        .HasColumnName("assignment_id");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("changed_by_user_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("FromStatus")
                        .HasColumnType("integer")
                        .HasColumnName("from_status");

                    b.Property<int>("ToStatus")
                        .HasColumnType("integer")
                        .HasColumnName("to_status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_assignment_status_history");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("ix_assignment_status_history_assignment_id");

                    b.ToTable("assignment_status_history", "docflow");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.DeadlineExtension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("integer")
                        .HasColumnName("assignment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("InitiatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("initiated_by_user_id");

                    b.Property<DateOnly>("NewDeadline")
                        .HasColumnType("date")
                        .HasColumnName("new_deadline");

                    b.Property<DateOnly>("OldDeadline")
                        .HasColumnType("date")
                        .HasColumnName("old_deadline");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_deadline_extension");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("ix_deadline_extension_assignment_id");

                    b.ToTable("deadline_extension", "docflow");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.DeadlineExtensionFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ExtensionId")
                        .HasColumnType("integer")
                        .HasColumnName("extension_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("stored_file_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_deadline_extension_file");

                    b.HasIndex("ExtensionId")
                        .HasDatabaseName("ix_deadline_extension_file_extension_id");

                    b.ToTable("deadline_extension_file", "docflow");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AggregatedStatus")
                        .HasColumnType("integer")
                        .HasColumnName("aggregated_status");

                    b.Property<short>("Classification")
                        .HasColumnType("smallint")
                        .HasColumnName("classification");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DirectionFlag")
                        .HasColumnType("integer")
                        .HasColumnName("direction_flag");

                    b.Property<int>("DivisionId")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<string>("FullText")
                        .HasColumnType("text")
                        .HasColumnName("full_text");

                    b.Property<int?>("InspectorUserId")
                        .HasColumnType("integer")
                        .HasColumnName("inspector_user_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateOnly>("RegDate")
                        .HasColumnType("date")
                        .HasColumnName("reg_date");

                    b.Property<string>("RegNumber")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reg_number");

                    b.Property<int?>("RegisteredByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("registered_by_user_id");

                    b.Property<string>("ShortContent")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("short_content");

                    b.Property<string>("Source")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_document");

                    b.HasIndex("RegDate")
                        .HasDatabaseName("ix_document_reg_date");

                    b.HasIndex("RegNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_document_reg_number");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_document_type_id");

                    b.HasIndex("AggregatedStatus", "UpdatedAt")
                        .HasDatabaseName("ix_document_aggregated_status_updated_at");

                    b.HasIndex("DivisionId", "Classification")
                        .HasDatabaseName("ix_document_division_id_classification");

                    b.ToTable("document", "docflow", t =>
                        {
                            t.HasCheckConstraint("chk_document_aggregated_status", "aggregated_status IN (0, 1, 2, 3, 4, 5, 6)");

                            t.HasCheckConstraint("chk_document_direction_flag", "direction_flag IN (1, 2, 3)");

                            t.HasCheckConstraint("chk_document_priority", "priority IS NULL OR priority IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssigneeUserId")
                        .HasColumnType("integer")
                        .HasColumnName("assignee_user_id");

                    b.Property<int?>("ControllerUserId")
                        .HasColumnType("integer")
                        .HasColumnName("controller_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("Deadline")
                        .HasColumnType("date")
                        .HasColumnName("deadline");

                    b.Property<int>("DivisionId")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("UseCommonDeadline")
                        .HasColumnType("boolean")
                        .HasColumnName("use_common_deadline");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_document_assignment");

                    b.HasIndex("AssigneeUserId")
                        .HasDatabaseName("ix_document_assignment_assignee_user_id");

                    b.HasIndex("DivisionId")
                        .HasDatabaseName("ix_document_assignment_division_id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_document_assignment_document_id");

                    b.HasIndex("DocumentId", "DivisionId")
                        .IsUnique()
                        .HasDatabaseName("ix_document_assignment_document_id_division_id");

                    b.ToTable("document_assignment", "docflow", t =>
                        {
                            t.HasCheckConstraint("chk_assignment_status", "status IN (1, 2, 3, 4, 5, 6, 7)");
                        });
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("stored_file_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_document_attachment");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_document_attachment_document_id");

                    b.ToTable("document_attachment", "docflow");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorUserId")
                        .HasColumnType("integer")
                        .HasColumnName("author_user_id");

                    b.Property<int>("CommentType")
                        .HasColumnType("integer")
                        .HasColumnName("comment_type");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DocumentFileId")
                        .HasColumnType("integer")
                        .HasColumnName("document_file_id");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean")
                        .HasColumnName("is_edited");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_resolved");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_comment_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<int?>("ResolvedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_document_comment");

                    b.HasIndex("ParentCommentId")
                        .HasDatabaseName("ix_document_comment_parent_comment_id");

                    b.HasIndex("DocumentId", "CreatedAt")
                        .HasDatabaseName("ix_document_comment_document_id_created_at");

                    b.ToTable("document_comment", "docflow");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentCommentFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentId")
                        .HasColumnType("integer")
                        .HasColumnName("comment_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("stored_file_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_document_comment_file");

                    b.HasIndex("CommentId")
                        .HasDatabaseName("ix_document_comment_file_comment_id");

                    b.ToTable("document_comment_file", "docflow");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentCommentMention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentId")
                        .HasColumnType("integer")
                        .HasColumnName("comment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_document_comment_mention");

                    b.HasIndex("CommentId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_document_comment_mention_comment_id_user_id");

                    b.ToTable("document_comment_mention", "docflow");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("boolean")
                        .HasColumnName("is_latest");

                    b.Property<int>("Language")
                        .HasColumnType("integer")
                        .HasColumnName("language");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("stored_file_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("uploaded_by_user_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_document_file");

                    b.HasIndex("DocumentId", "IsLatest")
                        .HasDatabaseName("ix_document_file_document_id_is_latest");

                    b.ToTable("document_file", "docflow");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentIndexLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoreDocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("core_document_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<DateTime>("IndexedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("indexed_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_document_index_link");

                    b.HasIndex("CoreDocumentId")
                        .HasDatabaseName("ix_document_index_link_core_document_id");

                    b.HasIndex("DocumentId")
                        .IsUnique()
                        .HasDatabaseName("ix_document_index_link_document_id");

                    b.ToTable("document_index_link", "docflow");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Group")
                        .HasColumnType("integer")
                        .HasColumnName("group");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_document_type");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_document_type_name");

                    b.ToTable("document_type", "docflow", t =>
                        {
                            t.HasCheckConstraint("chk_document_type_group", "\"group\" IN (1, 2)");
                        });
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("AboutDeadline")
                        .HasColumnType("date")
                        .HasColumnName("about_deadline");

                    b.Property<string>("ArgumentsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arguments_json");

                    b.Property<int?>("AssignmentId")
                        .HasColumnType("integer")
                        .HasColumnName("assignment_id");

                    b.Property<int?>("CommentId")
                        .HasColumnType("integer")
                        .HasColumnName("comment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("MessageKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("message_key");

                    b.Property<int>("RecipientUserId")
                        .HasColumnType("integer")
                        .HasColumnName("recipient_user_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_notification");

                    b.HasIndex("CommentId")
                        .HasDatabaseName("ix_notification_comment_id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_notification_document_id");

                    b.HasIndex("AssignmentId", "Type", "AboutDeadline")
                        .HasDatabaseName("ix_notification_assignment_id_type_about_deadline");

                    b.HasIndex("RecipientUserId", "IsRead", "CreatedAt")
                        .HasDatabaseName("ix_notification_recipient_user_id_is_read_created_at");

                    b.ToTable("notification", "docflow");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.StatusHistoryFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<int>("StatusHistoryId")
                        .HasColumnType("integer")
                        .HasColumnName("status_history_id");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("stored_file_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_status_history_file");

                    b.HasIndex("StatusHistoryId")
                        .HasDatabaseName("ix_status_history_file_status_history_id");

                    b.ToTable("status_history_file", "docflow");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_user_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_system_setting");

                    b.ToTable("system_setting", "docflow");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.AssignmentReassignment", b =>
                {
                    b.HasOne("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentAssignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_reassignment_document_assignments_assignment_id");

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.AssignmentStatusHistory", b =>
                {
                    b.HasOne("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentAssignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_status_history_document_assignments_assignment_id");

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.DeadlineExtension", b =>
                {
                    b.HasOne("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentAssignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deadline_extension_document_assignments_assignment_id");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.DeadlineExtensionFile", b =>
                {
                    b.HasOne("ISC.AI.Modules.DocFlow.Domain.Entities.DeadlineExtension", "Extension")
                        .WithMany()
                        .HasForeignKey("ExtensionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deadline_extension_file_deadline_extension_extension_id");

                    b.Navigation("Extension");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.Document", b =>
                {
                    b.HasOne("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_document_document_types_type_id");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentAssignment", b =>
                {
                    b.HasOne("ISC.AI.Modules.DocFlow.Domain.Entities.Document", "Document")
                        .WithMany("Assignments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_assignment_documents_document_id");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentAttachment", b =>
                {
                    b.HasOne("ISC.AI.Modules.DocFlow.Domain.Entities.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_attachment_documents_document_id");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentComment", b =>
                {
                    b.HasOne("ISC.AI.Modules.DocFlow.Domain.Entities.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_comment_documents_document_id");

                    b.HasOne("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentComment", null)
                        .WithMany()
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_document_comment_document_comment_parent_comment_id");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentCommentFile", b =>
                {
                    b.HasOne("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentComment", "Comment")
                        .WithMany("Files")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_comment_file_document_comment_comment_id");

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentCommentMention", b =>
                {
                    b.HasOne("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentComment", null)
                        .WithMany("Mentions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_comment_mention_document_comment_comment_id");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentFile", b =>
                {
                    b.HasOne("ISC.AI.Modules.DocFlow.Domain.Entities.Document", null)
                        .WithMany("Files")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_file_document_document_id");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentIndexLink", b =>
                {
                    b.HasOne("ISC.AI.Modules.DocFlow.Domain.Entities.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_index_link_document_document_id");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.Notification", b =>
                {
                    b.HasOne("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentAssignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notification_document_assignment_assignment_id");

                    b.HasOne("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentComment", null)
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notification_document_comment_comment_id");

                    b.HasOne("ISC.AI.Modules.DocFlow.Domain.Entities.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notification_document_document_id");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.StatusHistoryFile", b =>
                {
                    b.HasOne("ISC.AI.Modules.DocFlow.Domain.Entities.AssignmentStatusHistory", "StatusHistory")
                        .WithMany()
                        .HasForeignKey("StatusHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_status_history_file_assignment_status_history_status_histor");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.Document", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Files");
                });

            modelBuilder.Entity("ISC.AI.Modules.DocFlow.Domain.Entities.DocumentComment", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Mentions");
                });
#pragma warning restore 612, 618
        }
    }
}
