// <auto-generated />
using System;
using ISC.AI.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace ISC.AI.Persistence.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    partial class CoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("core")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ISC.AI.Persistence.Entities.AppUserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("displayName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isDeleted");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("userName");

                    b.HasKey("Id")
                        .HasName("pK_appUser");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("ixAppUserUsername");

                    b.ToTable("appUser", "core");
                });

            modelBuilder.Entity("ISC.AI.Persistence.Entities.ChunkEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("Classification")
                        .HasColumnType("smallint")
                        .HasColumnName("classification");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<int>("DivisionId")
                        .HasColumnType("integer")
                        .HasColumnName("divisionId");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("documentId");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isCurrent");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id")
                        .HasName("pK_chunk");

                    b.HasIndex("Classification", "DivisionId")
                        .HasDatabaseName("ixChunkClassificationDivision");

                    b.HasIndex("DocumentId", "Ordinal")
                        .HasDatabaseName("ixChunkDocumentOrdinal");

                    b.ToTable("chunk", "core");
                });

            modelBuilder.Entity("ISC.AI.Persistence.Entities.ClearanceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isDeleted");

                    b.Property<short>("MaxClassification")
                        .HasColumnType("smallint")
                        .HasColumnName("maxClassification");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("pK_clearance");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ixClearanceUser");

                    b.ToTable("clearance", "core");
                });

            modelBuilder.Entity("ISC.AI.Persistence.Entities.DocumentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("Classification")
                        .HasColumnType("smallint")
                        .HasColumnName("classification");

                    b.Property<byte[]>("ContentHash")
                        .HasColumnType("bytea")
                        .HasColumnName("contentHash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<int>("DivisionId")
                        .HasColumnType("integer")
                        .HasColumnName("divisionId");

                    b.Property<DateOnly?>("DocDate")
                        .HasColumnType("date")
                        .HasColumnName("docDate");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("docType");

                    b.Property<string>("Source")
                        .HasMaxLength(700)
                        .HasColumnType("character varying(700)")
                        .HasColumnName("source");

                    b.Property<string>("StorageUri")
                        .HasColumnType("text")
                        .HasColumnName("storageUri");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id")
                        .HasName("pK_document");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("ixDocumentContentHash");

                    b.HasIndex("Classification", "DivisionId")
                        .HasDatabaseName("ixDocumentClassificationDivision");

                    b.ToTable("document", "core");
                });

            modelBuilder.Entity("ISC.AI.Persistence.Entities.EmbeddingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChunkId")
                        .HasColumnType("integer")
                        .HasColumnName("chunkId");

                    b.Property<short>("Classification")
                        .HasColumnType("smallint")
                        .HasColumnName("classification");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<int>("DivisionId")
                        .HasColumnType("integer")
                        .HasColumnName("divisionId");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isCurrent");

                    b.Property<string>("ModelKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modelKey");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id")
                        .HasName("pK_embedding");

                    b.HasIndex("ChunkId")
                        .HasDatabaseName("iX_embedding_chunkId");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ixEmbeddingVectorHnsw");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("Classification", "DivisionId")
                        .HasDatabaseName("ixEmbeddingClassificationDivision");

                    b.ToTable("embedding", "core");
                });

            modelBuilder.Entity("ISC.AI.Persistence.Entities.IndexingJobEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completedAt");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("documentId");

                    b.Property<string>("Error")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("error");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id")
                        .HasName("pK_indexingJob");

                    b.HasIndex("Status")
                        .HasDatabaseName("ixIndexingJobStatus");

                    b.ToTable("indexingJob", "core");
                });

            modelBuilder.Entity("ISC.AI.Persistence.Entities.ChunkEntity", b =>
                {
                    b.HasOne("ISC.AI.Persistence.Entities.DocumentEntity", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_chunk_documents_documentId");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ISC.AI.Persistence.Entities.ClearanceEntity", b =>
                {
                    b.HasOne("ISC.AI.Persistence.Entities.AppUserEntity", "User")
                        .WithOne("Clearance")
                        .HasForeignKey("ISC.AI.Persistence.Entities.ClearanceEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_clearance_appUser_userId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ISC.AI.Persistence.Entities.EmbeddingEntity", b =>
                {
                    b.HasOne("ISC.AI.Persistence.Entities.ChunkEntity", "Chunk")
                        .WithMany()
                        .HasForeignKey("ChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_embedding_chunk_chunkId");

                    b.Navigation("Chunk");
                });

            modelBuilder.Entity("ISC.AI.Persistence.Entities.AppUserEntity", b =>
                {
                    b.Navigation("Clearance");
                });

            modelBuilder.Entity("ISC.AI.Persistence.Entities.DocumentEntity", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
