<Project Sdk="Microsoft.NET.Sdk">

  <!-- Манифест профиля: собирает Application, Data, UI в единый профиль (IProfile). -->
  <ItemGroup>
    <ProjectReference Include="..\ISC.AI.Profile.Inspector.Application\ISC.AI.Profile.Inspector.Application.csproj" />
    <ProjectReference Include="..\ISC.AI.Profile.Inspector.Data\ISC.AI.Profile.Inspector.Data.csproj" />
    <ProjectReference Include="..\ISC.AI.Profile.Inspector.UI\ISC.AI.Profile.Inspector.UI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

</Project>
