// <auto-generated />
using System;
using ISC.AI.Modules.Media.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace ISC.AI.Modules.Media.Data.Migrations
{
    [DbContext(typeof(MediaDbContext))]
    [Migration("20260917121139_SearchSessions")]
    partial class SearchSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("media")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ISC.AI.Modules.Media.Data.Entities.Face", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("integer")
                        .HasColumnName("asset_id");

                    b.Property<float>("BoxHeight")
                        .HasColumnType("real")
                        .HasColumnName("box_height");

                    b.Property<float>("BoxWidth")
                        .HasColumnType("real")
                        .HasColumnName("box_width");

                    b.Property<float>("BoxX")
                        .HasColumnType("real")
                        .HasColumnName("box_x");

                    b.Property<float>("BoxY")
                        .HasColumnType("real")
                        .HasColumnName("box_y");

                    b.Property<short>("Classification")
                        .HasColumnType("smallint")
                        .HasColumnName("classification");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CropStoredFileName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("crop_stored_file_name");

                    b.Property<float>("DetectionScore")
                        .HasColumnType("real")
                        .HasColumnName("detection_score");

                    b.Property<int>("DivisionId")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<int?>("FrameId")
                        .HasColumnType("integer")
                        .HasColumnName("frame_id");

                    b.PrimitiveCollection<float[]>("Landmarks")
                        .IsRequired()
                        .HasColumnType("real[]")
                        .HasColumnName("landmarks");

                    b.Property<bool>("QualityAcceptable")
                        .HasColumnType("boolean")
                        .HasColumnName("quality_acceptable");

                    b.Property<string>("QualityReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("quality_reason");

                    b.Property<float>("QualityScore")
                        .HasColumnType("real")
                        .HasColumnName("quality_score");

                    b.Property<int?>("TrackId")
                        .HasColumnType("integer")
                        .HasColumnName("track_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_face");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_face_asset_id");

                    b.HasIndex("CropStoredFileName")
                        .IsUnique()
                        .HasDatabaseName("ix_face_crop_stored_file_name")
                        .HasFilter("crop_stored_file_name IS NOT NULL");

                    b.HasIndex("FrameId")
                        .HasDatabaseName("ix_face_frame_id");

                    b.HasIndex("Classification", "DivisionId")
                        .HasDatabaseName("ix_face_classification_division_id");

                    b.ToTable("face", "media");
                });

            modelBuilder.Entity("ISC.AI.Modules.Media.Data.Entities.FaceTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("integer")
                        .HasColumnName("asset_id");

                    b.Property<short>("Classification")
                        .HasColumnType("smallint")
                        .HasColumnName("classification");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DivisionId")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(128)")
                        .HasColumnName("embedding");

                    b.Property<int>("FaceId")
                        .HasColumnType("integer")
                        .HasColumnName("face_id");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_current");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_version");

                    b.Property<bool>("QualityAcceptable")
                        .HasColumnType("boolean")
                        .HasColumnName("quality_acceptable");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_face_template");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_face_template_asset_id");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_face_template_embedding")
                        .HasAnnotation("Npgsql:StorageParameter:ef_construction", 512)
                        .HasAnnotation("Npgsql:StorageParameter:m", 16);

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("FaceId")
                        .IsUnique()
                        .HasDatabaseName("ix_face_template_face_id");

                    b.HasIndex("Classification", "DivisionId")
                        .HasDatabaseName("ix_face_template_classification_division_id");

                    b.ToTable("face_template", "media");
                });

            modelBuilder.Entity("ISC.AI.Modules.Media.Data.Entities.MediaAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<DateTimeOffset?>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<short>("Classification")
                        .HasColumnType("smallint")
                        .HasColumnName("classification");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DetectorVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("detector_version");

                    b.Property<int>("DivisionId")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("EmbedderVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("embedder_version");

                    b.Property<string>("IndexError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("index_error");

                    b.Property<int>("IndexStatus")
                        .HasColumnType("integer")
                        .HasColumnName("index_status");

                    b.Property<DateTime?>("IndexedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("indexed_at");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_current");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("Source")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stored_file_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UploadedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_asset");

                    b.HasIndex("IndexStatus")
                        .HasDatabaseName("ix_asset_index_status");

                    b.HasIndex("StoredFileName")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_stored_file_name");

                    b.HasIndex("Classification", "DivisionId")
                        .HasDatabaseName("ix_asset_classification_division_id");

                    b.HasIndex("DivisionId", "ContentHash")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_division_id_content_hash");

                    b.ToTable("asset", "media");
                });

            modelBuilder.Entity("ISC.AI.Modules.Media.Data.Entities.MediaFrame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("integer")
                        .HasColumnName("asset_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<long>("TimestampMs")
                        .HasColumnType("bigint")
                        .HasColumnName("timestamp_ms");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_frame");

                    b.HasIndex("AssetId", "Index")
                        .IsUnique()
                        .HasDatabaseName("ix_frame_asset_id_index");

                    b.ToTable("frame", "media");
                });

            modelBuilder.Entity("ISC.AI.Modules.Media.Data.Entities.SearchCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("integer")
                        .HasColumnName("asset_id");

                    b.Property<short>("Classification")
                        .HasColumnType("smallint")
                        .HasColumnName("classification");

                    b.Property<double>("CosineDistance")
                        .HasColumnType("double precision")
                        .HasColumnName("cosine_distance");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CropStoredFileName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("crop_stored_file_name");

                    b.Property<int>("DivisionId")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<int>("FaceId")
                        .HasColumnType("integer")
                        .HasColumnName("face_id");

                    b.Property<int?>("FrameIndex")
                        .HasColumnType("integer")
                        .HasColumnName("frame_index");

                    b.Property<long?>("FrameTimestampMs")
                        .HasColumnType("bigint")
                        .HasColumnName("frame_timestamp_ms");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_version");

                    b.Property<int?>("PersonRef")
                        .HasColumnType("integer")
                        .HasColumnName("person_ref");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_search_candidate");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_search_candidate_status");

                    b.HasIndex("Classification", "DivisionId")
                        .HasDatabaseName("ix_search_candidate_classification_division_id");

                    b.HasIndex("SessionId", "Rank")
                        .IsUnique()
                        .HasDatabaseName("ix_search_candidate_session_id_rank");

                    b.ToTable("search_candidate", "media");
                });

            modelBuilder.Entity("ISC.AI.Modules.Media.Data.Entities.SearchSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorizationRef")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("authorization_ref");

                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    b.PrimitiveCollection<int[]>("CaseIds")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("case_ids");

                    b.Property<short>("Classification")
                        .HasColumnType("smallint")
                        .HasColumnName("classification");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DetectorVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("detector_version");

                    b.Property<int>("DivisionId")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<string>("EmbedderVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("embedder_version");

                    b.Property<int>("HnswEfSearch")
                        .HasColumnType("integer")
                        .HasColumnName("hnsw_ef_search");

                    b.Property<double?>("MaxCosineDistance")
                        .HasColumnType("double precision")
                        .HasColumnName("max_cosine_distance");

                    b.Property<string>("ProbeCropStoredFileName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("probe_crop_stored_file_name");

                    b.Property<int?>("ProbeFaceId")
                        .HasColumnType("integer")
                        .HasColumnName("probe_face_id");

                    b.Property<string>("ProbeSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("probe_sha256");

                    b.Property<int?>("RequestedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("requested_by_user_id");

                    b.Property<int>("Scope")
                        .HasColumnType("integer")
                        .HasColumnName("scope");

                    b.Property<int>("TopK")
                        .HasColumnType("integer")
                        .HasColumnName("top_k");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_search_session");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_search_session_case_id");

                    b.HasIndex("ProbeCropStoredFileName")
                        .IsUnique()
                        .HasDatabaseName("ix_search_session_probe_crop_stored_file_name")
                        .HasFilter("probe_crop_stored_file_name IS NOT NULL");

                    b.HasIndex("Classification", "DivisionId")
                        .HasDatabaseName("ix_search_session_classification_division_id");

                    b.ToTable("search_session", "media");
                });

            modelBuilder.Entity("ISC.AI.Modules.Media.Data.Entities.VerificationDecisionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at_utc");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("rationale");

                    b.Property<int>("Stage")
                        .HasColumnType("integer")
                        .HasColumnName("stage");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer")
                        .HasColumnName("subject_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Verdict")
                        .HasColumnType("integer")
                        .HasColumnName("verdict");

                    b.HasKey("Id")
                        .HasName("pk_verification_decision");

                    b.HasIndex("CandidateId", "Stage")
                        .IsUnique()
                        .HasDatabaseName("ix_verification_decision_candidate_id_stage");

                    b.ToTable("verification_decision", "media");
                });

            modelBuilder.Entity("ISC.AI.Modules.Media.Data.Entities.Face", b =>
                {
                    b.HasOne("ISC.AI.Modules.Media.Data.Entities.MediaAsset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_face_assets_asset_id");

                    b.HasOne("ISC.AI.Modules.Media.Data.Entities.MediaFrame", "Frame")
                        .WithMany()
                        .HasForeignKey("FrameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_face_frames_frame_id");

                    b.Navigation("Asset");

                    b.Navigation("Frame");
                });

            modelBuilder.Entity("ISC.AI.Modules.Media.Data.Entities.FaceTemplate", b =>
                {
                    b.HasOne("ISC.AI.Modules.Media.Data.Entities.MediaAsset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_face_template_assets_asset_id");

                    b.HasOne("ISC.AI.Modules.Media.Data.Entities.Face", "Face")
                        .WithOne()
                        .HasForeignKey("ISC.AI.Modules.Media.Data.Entities.FaceTemplate", "FaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_face_template_face_face_id");

                    b.Navigation("Face");
                });

            modelBuilder.Entity("ISC.AI.Modules.Media.Data.Entities.MediaFrame", b =>
                {
                    b.HasOne("ISC.AI.Modules.Media.Data.Entities.MediaAsset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_frame_asset_asset_id");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("ISC.AI.Modules.Media.Data.Entities.SearchCandidate", b =>
                {
                    b.HasOne("ISC.AI.Modules.Media.Data.Entities.SearchSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_search_candidate_search_sessions_session_id");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ISC.AI.Modules.Media.Data.Entities.VerificationDecisionEntity", b =>
                {
                    b.HasOne("ISC.AI.Modules.Media.Data.Entities.SearchCandidate", null)
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_verification_decision_search_candidate_candidate_id");
                });
#pragma warning restore 612, 618
        }
    }
}
