// <auto-generated />
using System;
using ISC.AI.Profile.Investigation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ISC.AI.Profile.Investigation.Data.Migrations
{
    [DbContext(typeof(InvestigationDbContext))]
    [Migration("20260930110833_AccessMatrix")]
    partial class AccessMatrix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("investigation")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.Appearance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer")
                        .HasColumnName("candidate_id");

                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    b.Property<short>("Classification")
                        .HasColumnType("smallint")
                        .HasColumnName("classification");

                    b.Property<DateTime>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at_utc");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DivisionId")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<int>("ExpertUserId")
                        .HasColumnType("integer")
                        .HasColumnName("expert_user_id");

                    b.Property<int?>("FrameIndex")
                        .HasColumnType("integer")
                        .HasColumnName("frame_index");

                    b.Property<long?>("FrameTimestampMs")
                        .HasColumnType("bigint")
                        .HasColumnName("frame_timestamp_ms");

                    b.Property<int>("MediaAssetId")
                        .HasColumnType("integer")
                        .HasColumnName("media_asset_id");

                    b.Property<int>("MediaFaceId")
                        .HasColumnType("integer")
                        .HasColumnName("media_face_id");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<int>("SearchSessionId")
                        .HasColumnType("integer")
                        .HasColumnName("search_session_id");

                    b.Property<double>("Similarity")
                        .HasColumnType("double precision")
                        .HasColumnName("similarity");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VerifierUserId")
                        .HasColumnType("integer")
                        .HasColumnName("verifier_user_id");

                    b.HasKey("Id")
                        .HasName("pk_appearance");

                    b.HasIndex("CandidateId")
                        .IsUnique()
                        .HasDatabaseName("ix_appearance_candidate_id");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_appearance_case_id");

                    b.HasIndex("MediaAssetId")
                        .HasDatabaseName("ix_appearance_media_asset_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_appearance_person_id");

                    b.ToTable("appearance", "investigation");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.CaseClosureAct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetsAffected")
                        .HasColumnType("integer")
                        .HasColumnName("assets_affected");

                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CropsRemoved")
                        .HasColumnType("integer")
                        .HasColumnName("crops_removed");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<int?>("ExecutedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("executed_by_user_id");

                    b.Property<int>("MediaAssetsTotal")
                        .HasColumnType("integer")
                        .HasColumnName("media_assets_total");

                    b.Property<int>("TemplatesRemoved")
                        .HasColumnType("integer")
                        .HasColumnName("templates_removed");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_case_closure_act");

                    b.HasIndex("CaseId")
                        .IsUnique()
                        .HasDatabaseName("ix_case_closure_act_case_id");

                    b.ToTable("case_closure_act", "investigation");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.CaseDocumentLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DocFlowDocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("doc_flow_document_id");

                    b.Property<int?>("LinkedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("linked_by_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_case_document_link");

                    b.HasIndex("CaseId", "DocFlowDocumentId")
                        .IsUnique()
                        .HasDatabaseName("ix_case_document_link_case_id_doc_flow_document_id");

                    b.ToTable("case_document_link", "investigation");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.CaseFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Basis")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("basis");

                    b.Property<short>("Classification")
                        .HasColumnType("smallint")
                        .HasColumnName("classification");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("DivisionId")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<string>("InitiatorDetails")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("initiator_details");

                    b.Property<string>("InitiatorName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("initiator_name");

                    b.Property<string>("InitiatorPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("initiator_phone");

                    b.Property<int?>("InitiatorPositionId")
                        .HasColumnType("integer")
                        .HasColumnName("initiator_position_id");

                    b.Property<int?>("InitiatorRankId")
                        .HasColumnType("integer")
                        .HasColumnName("initiator_rank_id");

                    b.Property<int?>("InitiatorUnitId")
                        .HasColumnType("integer")
                        .HasColumnName("initiator_unit_id");

                    b.Property<int?>("InvestigatorUserId")
                        .HasColumnType("integer")
                        .HasColumnName("investigator_user_id");

                    b.Property<string>("Justification")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("justification");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("number");

                    b.Property<DateOnly>("OpenedAt")
                        .HasColumnType("date")
                        .HasColumnName("opened_at");

                    b.Property<string>("Purpose")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("purpose");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TaskNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("task_notes");

                    b.Property<string>("TaskNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("task_number");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_case_file");

                    b.HasIndex("InitiatorPositionId")
                        .HasDatabaseName("ix_case_file_initiator_position_id");

                    b.HasIndex("InitiatorRankId")
                        .HasDatabaseName("ix_case_file_initiator_rank_id");

                    b.HasIndex("InitiatorUnitId")
                        .HasDatabaseName("ix_case_file_initiator_unit_id");

                    b.HasIndex("InvestigatorUserId")
                        .HasDatabaseName("ix_case_file_investigator_user_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_case_file_status");

                    b.HasIndex("Classification", "DivisionId")
                        .HasDatabaseName("ix_case_file_classification_division_id");

                    b.HasIndex("DivisionId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_case_file_division_id_number");

                    b.ToTable("case_file", "investigation", t =>
                        {
                            t.HasCheckConstraint("ck_case_file_task_requisites", "(kind = 4 AND initiator_unit_id IS NOT NULL AND coalesce(btrim(task_number), '') <> '' AND coalesce(btrim(justification), '') <> '' AND coalesce(btrim(purpose), '') <> '') OR (kind <> 4 AND task_number IS NULL AND initiator_unit_id IS NULL AND initiator_name IS NULL AND initiator_rank_id IS NULL AND initiator_position_id IS NULL AND initiator_phone IS NULL AND initiator_details IS NULL AND justification IS NULL AND purpose IS NULL AND task_notes IS NULL)");
                        });
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.CaseMediaLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("LinkedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("linked_by_user_id");

                    b.Property<int>("MediaAssetId")
                        .HasColumnType("integer")
                        .HasColumnName("media_asset_id");

                    b.Property<string>("Place")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("place");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_case_media_link");

                    b.HasIndex("MediaAssetId")
                        .HasDatabaseName("ix_case_media_link_media_asset_id");

                    b.HasIndex("CaseId", "MediaAssetId")
                        .IsUnique()
                        .HasDatabaseName("ix_case_media_link_case_id_media_asset_id");

                    b.ToTable("case_media_link", "investigation");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.CaseReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    b.Property<short>("Classification")
                        .HasColumnType("smallint")
                        .HasColumnName("classification");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("CurrentRevision")
                        .HasColumnType("integer")
                        .HasColumnName("current_revision");

                    b.Property<int>("DivisionId")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<int?>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<DateOnly>("ReportDate")
                        .HasColumnType("date")
                        .HasColumnName("report_date");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_case_report");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_case_report_person_id");

                    b.HasIndex("CaseId", "ReportDate")
                        .HasDatabaseName("ix_case_report_case_id_report_date");

                    b.ToTable("case_report", "investigation");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.CaseReportPermit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("Classification")
                        .HasColumnType("smallint")
                        .HasColumnName("classification");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<int?>("DecidedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("decided_by_user_id");

                    b.Property<int>("DivisionId")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<int>("ReportId")
                        .HasColumnType("integer")
                        .HasColumnName("report_id");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("requested_by_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_case_report_permit");

                    b.HasIndex("ReportId", "RequestedByUserId")
                        .HasDatabaseName("ix_case_report_permit_report_id_requested_by_user_id");

                    b.HasIndex("Status", "RequestedAt")
                        .HasDatabaseName("ix_case_report_permit_status_requested_at");

                    b.ToTable("case_report_permit", "investigation", t =>
                        {
                            t.HasCheckConstraint("ck_case_report_permit_reason", "btrim(reason) <> ''");
                        });
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.CaseReportRevision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorUserId")
                        .HasColumnType("integer")
                        .HasColumnName("author_user_id");

                    b.Property<short>("Classification")
                        .HasColumnType("smallint")
                        .HasColumnName("classification");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DivisionId")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<string>("EditReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("edit_reason");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<int?>("PermitId")
                        .HasColumnType("integer")
                        .HasColumnName("permit_id");

                    b.Property<int>("ReportId")
                        .HasColumnType("integer")
                        .HasColumnName("report_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_case_report_revision");

                    b.HasIndex("ReportId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_case_report_revision_report_id_number");

                    b.ToTable("case_report_revision", "investigation");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.Division", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_division");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_division_code")
                        .HasFilter("code IS NOT NULL");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_division_parent_id");

                    b.ToTable("division", "investigation");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.IntersectionReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    b.Property<short>("Classification")
                        .HasColumnType("smallint")
                        .HasColumnName("classification");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<int?>("DecidedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("decided_by_user_id");

                    b.Property<int>("Decision")
                        .HasColumnType("integer")
                        .HasColumnName("decision");

                    b.Property<int>("DivisionId")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<string>("KeyNormalized")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("key_normalized");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<int>("OtherCaseId")
                        .HasColumnType("integer")
                        .HasColumnName("other_case_id");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_intersection_review");

                    b.HasIndex("PersonId", "Kind", "KeyNormalized", "OtherCaseId")
                        .IsUnique()
                        .HasDatabaseName("ix_intersection_review_person_id_kind_key_normalized_other_cas");

                    b.ToTable("intersection_review", "investigation");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alias");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("BirthPlace")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("birth_place");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer")
                        .HasColumnName("birth_year");

                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    b.Property<short>("Classification")
                        .HasColumnType("smallint")
                        .HasColumnName("classification");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("display_name");

                    b.Property<int>("DivisionId")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<bool>("IsUnidentified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_unidentified");

                    b.Property<int?>("LinkTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("link_type_id");

                    b.Property<int?>("LinkedToPersonId")
                        .HasColumnType("integer")
                        .HasColumnName("linked_to_person_id");

                    b.Property<string>("NameNormalized")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name_normalized");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<string>("Residence")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("residence");

                    b.Property<string>("ResidenceNormalized")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("residence_normalized");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("RoleInCase")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("role_in_case");

                    b.Property<int?>("Sex")
                        .HasColumnType("integer")
                        .HasColumnName("sex");

                    b.Property<int?>("UnidentifiedNumber")
                        .HasColumnType("integer")
                        .HasColumnName("unidentified_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkPlace")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("work_place");

                    b.HasKey("Id")
                        .HasName("pk_person");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_person_case_id");

                    b.HasIndex("LinkTypeId")
                        .HasDatabaseName("ix_person_link_type_id");

                    b.HasIndex("LinkedToPersonId")
                        .HasDatabaseName("ix_person_linked_to_person_id");

                    b.HasIndex("NameNormalized")
                        .HasDatabaseName("ix_person_name_normalized");

                    b.HasIndex("ResidenceNormalized")
                        .HasDatabaseName("ix_person_residence_normalized");

                    b.HasIndex("CaseId", "UnidentifiedNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_person_case_id_unidentified_number")
                        .HasFilter("unidentified_number IS NOT NULL");

                    b.ToTable("person", "investigation", t =>
                        {
                            t.HasCheckConstraint("ck_person_birth_year_matches_date", "birth_date IS NULL OR birth_year = EXTRACT(YEAR FROM birth_date)");

                            t.HasCheckConstraint("ck_person_link_only_for_link_role", "(role = 2 OR (linked_to_person_id IS NULL AND link_type_id IS NULL)) AND (linked_to_person_id IS NULL OR linked_to_person_id <> id)");
                        });
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.PersonAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("Classification")
                        .HasColumnType("smallint")
                        .HasColumnName("classification");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DivisionId")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.Property<string>("TextNormalized")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text_normalized");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_person_address");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_person_address_person_id");

                    b.HasIndex("TextNormalized")
                        .HasDatabaseName("ix_person_address_text_normalized");

                    b.ToTable("person_address", "investigation");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.PersonVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("Classification")
                        .HasColumnType("smallint")
                        .HasColumnName("classification");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DivisionId")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<string>("Make")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<string>("PlateNormalized")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("plate_normalized");

                    b.Property<string>("PlateNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("plate_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_person_vehicle");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_person_vehicle_person_id");

                    b.HasIndex("PlateNormalized")
                        .HasDatabaseName("ix_person_vehicle_plate_normalized");

                    b.ToTable("person_vehicle", "investigation", t =>
                        {
                            t.HasCheckConstraint("ck_person_vehicle_plate_or_make", "coalesce(btrim(plate_number), '') <> '' OR coalesce(btrim(make), '') <> ''");
                        });
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.ReferenceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_reference_item");

                    b.HasIndex("Kind", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_reference_item_kind_name");

                    b.ToTable("reference_item", "investigation");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.ReferencePhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("added_by_user_id");

                    b.Property<short>("Classification")
                        .HasColumnType("smallint")
                        .HasColumnName("classification");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DivisionId")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<string>("LegalBasis")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("legal_basis");

                    b.Property<int>("MediaAssetId")
                        .HasColumnType("integer")
                        .HasColumnName("media_asset_id");

                    b.Property<int?>("MediaFaceId")
                        .HasColumnType("integer")
                        .HasColumnName("media_face_id");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<float?>("QualityScore")
                        .HasColumnType("real")
                        .HasColumnName("quality_score");

                    b.Property<DateOnly?>("ReviewDueAt")
                        .HasColumnType("date")
                        .HasColumnName("review_due_at");

                    b.Property<string>("Source")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("source");

                    b.Property<int?>("SupersededById")
                        .HasColumnType("integer")
                        .HasColumnName("superseded_by_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_reference_photo");

                    b.HasIndex("MediaAssetId")
                        .HasDatabaseName("ix_reference_photo_media_asset_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_reference_photo_person_id");

                    b.ToTable("reference_photo", "investigation");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsGranted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_granted");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("permission");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_role_permission");

                    b.HasIndex("Role", "Permission")
                        .IsUnique()
                        .HasDatabaseName("ix_role_permission_role_permission");

                    b.ToTable("role_permission", "investigation");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.SearchAuthorization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("IssuedAt")
                        .HasColumnType("date")
                        .HasColumnName("issued_at");

                    b.Property<int?>("IssuedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("issued_by_user_id");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reference");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_search_authorization");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_search_authorization_case_id");

                    b.ToTable("search_authorization", "investigation");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.UserRoleAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_role_assignment");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_role_assignment_user_id");

                    b.ToTable("user_role_assignment", "investigation");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.Appearance", b =>
                {
                    b.HasOne("ISC.AI.Profile.Investigation.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appearance_persons_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.CaseClosureAct", b =>
                {
                    b.HasOne("ISC.AI.Profile.Investigation.Domain.Entities.CaseFile", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_case_closure_act_cases_case_id");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.CaseDocumentLink", b =>
                {
                    b.HasOne("ISC.AI.Profile.Investigation.Domain.Entities.CaseFile", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_case_document_link_cases_case_id");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.CaseFile", b =>
                {
                    b.HasOne("ISC.AI.Profile.Investigation.Domain.Entities.ReferenceItem", null)
                        .WithMany()
                        .HasForeignKey("InitiatorPositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_case_file_reference_items_initiator_position_id");

                    b.HasOne("ISC.AI.Profile.Investigation.Domain.Entities.ReferenceItem", null)
                        .WithMany()
                        .HasForeignKey("InitiatorRankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_case_file_reference_items_initiator_rank_id");

                    b.HasOne("ISC.AI.Profile.Investigation.Domain.Entities.ReferenceItem", null)
                        .WithMany()
                        .HasForeignKey("InitiatorUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_case_file_reference_items_initiator_unit_id");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.CaseMediaLink", b =>
                {
                    b.HasOne("ISC.AI.Profile.Investigation.Domain.Entities.CaseFile", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_case_media_link_case_file_case_id");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.CaseReport", b =>
                {
                    b.HasOne("ISC.AI.Profile.Investigation.Domain.Entities.CaseFile", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_case_report_case_file_case_id");

                    b.HasOne("ISC.AI.Profile.Investigation.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_case_report_persons_person_id");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.CaseReportPermit", b =>
                {
                    b.HasOne("ISC.AI.Profile.Investigation.Domain.Entities.CaseReport", "Report")
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_case_report_permit_case_report_report_id");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.CaseReportRevision", b =>
                {
                    b.HasOne("ISC.AI.Profile.Investigation.Domain.Entities.CaseReport", "Report")
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_case_report_revision_case_report_report_id");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.Division", b =>
                {
                    b.HasOne("ISC.AI.Profile.Investigation.Domain.Entities.Division", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_division_division_parent_id");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.IntersectionReview", b =>
                {
                    b.HasOne("ISC.AI.Profile.Investigation.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_intersection_review_persons_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.Person", b =>
                {
                    b.HasOne("ISC.AI.Profile.Investigation.Domain.Entities.CaseFile", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_case_file_case_id");

                    b.HasOne("ISC.AI.Profile.Investigation.Domain.Entities.ReferenceItem", null)
                        .WithMany()
                        .HasForeignKey("LinkTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_person_reference_items_link_type_id");

                    b.HasOne("ISC.AI.Profile.Investigation.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("LinkedToPersonId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_person_person_linked_to_person_id");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.PersonAddress", b =>
                {
                    b.HasOne("ISC.AI.Profile.Investigation.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_address_persons_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.PersonVehicle", b =>
                {
                    b.HasOne("ISC.AI.Profile.Investigation.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_vehicle_person_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.ReferencePhoto", b =>
                {
                    b.HasOne("ISC.AI.Profile.Investigation.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reference_photo_person_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.SearchAuthorization", b =>
                {
                    b.HasOne("ISC.AI.Profile.Investigation.Domain.Entities.CaseFile", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_search_authorization_case_file_case_id");

                    b.Navigation("Case");
                });
#pragma warning restore 612, 618
        }
    }
}
