// <auto-generated />
using System;
using ISC.AI.Profile.Investigation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ISC.AI.Profile.Investigation.Data.Migrations
{
    [DbContext(typeof(InvestigationDbContext))]
    [Migration("20260918055753_PersonCaseIndex")]
    partial class PersonCaseIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("investigation")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.Appearance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer")
                        .HasColumnName("candidate_id");

                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    b.Property<short>("Classification")
                        .HasColumnType("smallint")
                        .HasColumnName("classification");

                    b.Property<DateTime>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at_utc");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DivisionId")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<int>("ExpertUserId")
                        .HasColumnType("integer")
                        .HasColumnName("expert_user_id");

                    b.Property<int?>("FrameIndex")
                        .HasColumnType("integer")
                        .HasColumnName("frame_index");

                    b.Property<long?>("FrameTimestampMs")
                        .HasColumnType("bigint")
                        .HasColumnName("frame_timestamp_ms");

                    b.Property<int>("MediaAssetId")
                        .HasColumnType("integer")
                        .HasColumnName("media_asset_id");

                    b.Property<int>("MediaFaceId")
                        .HasColumnType("integer")
                        .HasColumnName("media_face_id");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<int>("SearchSessionId")
                        .HasColumnType("integer")
                        .HasColumnName("search_session_id");

                    b.Property<double>("Similarity")
                        .HasColumnType("double precision")
                        .HasColumnName("similarity");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VerifierUserId")
                        .HasColumnType("integer")
                        .HasColumnName("verifier_user_id");

                    b.HasKey("Id")
                        .HasName("pk_appearance");

                    b.HasIndex("CandidateId")
                        .IsUnique()
                        .HasDatabaseName("ix_appearance_candidate_id");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_appearance_case_id");

                    b.HasIndex("MediaAssetId")
                        .HasDatabaseName("ix_appearance_media_asset_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_appearance_person_id");

                    b.ToTable("appearance", "investigation");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.CaseDocumentLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DocFlowDocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("doc_flow_document_id");

                    b.Property<int?>("LinkedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("linked_by_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_case_document_link");

                    b.HasIndex("CaseId", "DocFlowDocumentId")
                        .IsUnique()
                        .HasDatabaseName("ix_case_document_link_case_id_doc_flow_document_id");

                    b.ToTable("case_document_link", "investigation");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.CaseFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Basis")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("basis");

                    b.Property<short>("Classification")
                        .HasColumnType("smallint")
                        .HasColumnName("classification");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("DivisionId")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<int?>("InvestigatorUserId")
                        .HasColumnType("integer")
                        .HasColumnName("investigator_user_id");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("number");

                    b.Property<DateOnly>("OpenedAt")
                        .HasColumnType("date")
                        .HasColumnName("opened_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_case_file");

                    b.HasIndex("InvestigatorUserId")
                        .HasDatabaseName("ix_case_file_investigator_user_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_case_file_status");

                    b.HasIndex("Classification", "DivisionId")
                        .HasDatabaseName("ix_case_file_classification_division_id");

                    b.HasIndex("DivisionId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_case_file_division_id_number");

                    b.ToTable("case_file", "investigation");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.CaseMediaLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("LinkedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("linked_by_user_id");

                    b.Property<int>("MediaAssetId")
                        .HasColumnType("integer")
                        .HasColumnName("media_asset_id");

                    b.Property<string>("Place")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("place");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_case_media_link");

                    b.HasIndex("MediaAssetId")
                        .HasDatabaseName("ix_case_media_link_media_asset_id");

                    b.HasIndex("CaseId", "MediaAssetId")
                        .IsUnique()
                        .HasDatabaseName("ix_case_media_link_case_id_media_asset_id");

                    b.ToTable("case_media_link", "investigation");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.Division", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_division");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_division_code")
                        .HasFilter("code IS NOT NULL");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_division_parent_id");

                    b.ToTable("division", "investigation");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    b.Property<short>("Classification")
                        .HasColumnType("smallint")
                        .HasColumnName("classification");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("display_name");

                    b.Property<int>("DivisionId")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<bool>("IsUnidentified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_unidentified");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<string>("RoleInCase")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("role_in_case");

                    b.Property<int?>("UnidentifiedNumber")
                        .HasColumnType("integer")
                        .HasColumnName("unidentified_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_person");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_person_case_id");

                    b.HasIndex("CaseId", "UnidentifiedNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_person_case_id_unidentified_number")
                        .HasFilter("unidentified_number IS NOT NULL");

                    b.ToTable("person", "investigation");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.ReferencePhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("added_by_user_id");

                    b.Property<short>("Classification")
                        .HasColumnType("smallint")
                        .HasColumnName("classification");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DivisionId")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<string>("LegalBasis")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("legal_basis");

                    b.Property<int>("MediaAssetId")
                        .HasColumnType("integer")
                        .HasColumnName("media_asset_id");

                    b.Property<int?>("MediaFaceId")
                        .HasColumnType("integer")
                        .HasColumnName("media_face_id");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<float?>("QualityScore")
                        .HasColumnType("real")
                        .HasColumnName("quality_score");

                    b.Property<DateOnly?>("ReviewDueAt")
                        .HasColumnType("date")
                        .HasColumnName("review_due_at");

                    b.Property<string>("Source")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("source");

                    b.Property<int?>("SupersededById")
                        .HasColumnType("integer")
                        .HasColumnName("superseded_by_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_reference_photo");

                    b.HasIndex("MediaAssetId")
                        .HasDatabaseName("ix_reference_photo_media_asset_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_reference_photo_person_id");

                    b.ToTable("reference_photo", "investigation");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.SearchAuthorization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("IssuedAt")
                        .HasColumnType("date")
                        .HasColumnName("issued_at");

                    b.Property<int?>("IssuedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("issued_by_user_id");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reference");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_search_authorization");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_search_authorization_case_id");

                    b.ToTable("search_authorization", "investigation");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.UserRoleAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_role_assignment");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_role_assignment_user_id");

                    b.ToTable("user_role_assignment", "investigation");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.Appearance", b =>
                {
                    b.HasOne("ISC.AI.Profile.Investigation.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appearance_persons_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.CaseDocumentLink", b =>
                {
                    b.HasOne("ISC.AI.Profile.Investigation.Domain.Entities.CaseFile", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_case_document_link_cases_case_id");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.CaseMediaLink", b =>
                {
                    b.HasOne("ISC.AI.Profile.Investigation.Domain.Entities.CaseFile", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_case_media_link_case_file_case_id");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.Division", b =>
                {
                    b.HasOne("ISC.AI.Profile.Investigation.Domain.Entities.Division", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_division_division_parent_id");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.Person", b =>
                {
                    b.HasOne("ISC.AI.Profile.Investigation.Domain.Entities.CaseFile", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_case_file_case_id");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.ReferencePhoto", b =>
                {
                    b.HasOne("ISC.AI.Profile.Investigation.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reference_photo_person_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ISC.AI.Profile.Investigation.Domain.Entities.SearchAuthorization", b =>
                {
                    b.HasOne("ISC.AI.Profile.Investigation.Domain.Entities.CaseFile", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_search_authorization_case_file_case_id");

                    b.Navigation("Case");
                });
#pragma warning restore 612, 618
        }
    }
}
