// <auto-generated />
using System;
using ISC.AI.Profile.Inspector.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ISC.AI.Profile.Inspector.Data.Migrations
{
    [DbContext(typeof(InspectorDbContext))]
    [Migration("20260825060747_AddDivisionKind")]
    partial class AddDivisionKind
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inspector")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ISC.AI.Profile.Inspector.Domain.Entities.ChunkRevisionLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChunkId")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("NormRevisionId")
                        .HasColumnType("integer")
                        .HasColumnName("norm_revision_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_chunk_revision_link");

                    b.HasIndex("ChunkId")
                        .HasDatabaseName("ix_chunk_revision_link_chunk_id");

                    b.HasIndex("NormRevisionId", "ChunkId")
                        .IsUnique()
                        .HasDatabaseName("ix_chunk_revision_link_norm_revision_id_chunk_id");

                    b.ToTable("chunk_revision_link", "inspector");
                });

            modelBuilder.Entity("ISC.AI.Profile.Inspector.Domain.Entities.Division", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_division");

                    b.HasIndex("Code")
                        .HasDatabaseName("ix_division_code");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_division_parent_id");

                    b.ToTable("division", "inspector");
                });

            modelBuilder.Entity("ISC.AI.Profile.Inspector.Domain.Entities.LegalNorm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("identifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_legal_norm");

                    b.HasIndex("Identifier")
                        .IsUnique()
                        .HasDatabaseName("ix_legal_norm_identifier");

                    b.ToTable("legal_norm", "inspector");
                });

            modelBuilder.Entity("ISC.AI.Profile.Inspector.Domain.Entities.MethodDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllCitationsConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("all_citations_confirmed");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("approved_by_user_id");

                    b.Property<string>("ArtifactKind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("artifact_kind");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("CitationsJson")
                        .HasColumnType("text")
                        .HasColumnName("citations_json");

                    b.Property<short>("Classification")
                        .HasColumnType("smallint")
                        .HasColumnName("classification");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("InspectionType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("inspection_type");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("scope");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_method_document");

                    b.HasIndex("ArtifactKind")
                        .HasDatabaseName("ix_method_document_artifact_kind");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_method_document_status");

                    b.HasIndex("Classification", "CreatedAt")
                        .HasDatabaseName("ix_method_document_classification_created_at");

                    b.ToTable("method_document", "inspector");
                });

            modelBuilder.Entity("ISC.AI.Profile.Inspector.Domain.Entities.NormDocumentLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<int>("LegalNormId")
                        .HasColumnType("integer")
                        .HasColumnName("legal_norm_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_norm_document_link");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_norm_document_link_document_id");

                    b.HasIndex("LegalNormId", "DocumentId")
                        .IsUnique()
                        .HasDatabaseName("ix_norm_document_link_legal_norm_id_document_id");

                    b.ToTable("norm_document_link", "inspector");
                });

            modelBuilder.Entity("ISC.AI.Profile.Inspector.Domain.Entities.NormRevision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<string>("ExternalEditionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_edition_id");

                    b.Property<int>("NormId")
                        .HasColumnType("integer")
                        .HasColumnName("norm_id");

                    b.Property<DateOnly?>("RepealedDate")
                        .HasColumnType("date")
                        .HasColumnName("repealed_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_norm_revision");

                    b.HasIndex("NormId", "ExternalEditionId")
                        .IsUnique()
                        .HasDatabaseName("ix_norm_revision_norm_id_external_edition_id")
                        .HasFilter("external_edition_id IS NOT NULL");

                    b.HasIndex("NormId", "Status")
                        .HasDatabaseName("ix_norm_revision_norm_id_status");

                    b.ToTable("norm_revision", "inspector");
                });

            modelBuilder.Entity("ISC.AI.Profile.Inspector.Domain.Entities.UserRoleAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_role_assignment");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_role_assignment_user_id");

                    b.ToTable("user_role_assignment", "inspector");
                });

            modelBuilder.Entity("ISC.AI.Profile.Inspector.Domain.Entities.Violation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Cause")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("cause");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DetectedAt")
                        .HasColumnType("date")
                        .HasColumnName("detected_at");

                    b.Property<int>("DivisionId")
                        .HasColumnType("integer")
                        .HasColumnName("division_id");

                    b.Property<string>("Recommendation")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("recommendation");

                    b.Property<string>("ReferenceDocRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reference_doc_ref");

                    b.Property<DateOnly?>("RemediationDeadline")
                        .HasColumnType("date")
                        .HasColumnName("remediation_deadline");

                    b.Property<int>("RemediationStatus")
                        .HasColumnType("integer")
                        .HasColumnName("remediation_status");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<string>("SourceAssignmentRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_assignment_ref");

                    b.Property<string>("SourceDocRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_doc_ref");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_violation");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_violation_category_id");

                    b.HasIndex("RemediationStatus")
                        .HasDatabaseName("ix_violation_remediation_status");

                    b.HasIndex("DivisionId", "DetectedAt")
                        .HasDatabaseName("ix_violation_division_id_detected_at");

                    b.HasIndex("RemediationStatus", "RemediationDeadline")
                        .HasDatabaseName("ix_violation_remediation_status_remediation_deadline");

                    b.ToTable("violation", "inspector");
                });

            modelBuilder.Entity("ISC.AI.Profile.Inspector.Domain.Entities.ViolationCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_violation_category");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_violation_category_parent_id");

                    b.ToTable("violation_category", "inspector");
                });

            modelBuilder.Entity("ISC.AI.Profile.Inspector.Domain.Entities.ChunkRevisionLink", b =>
                {
                    b.HasOne("ISC.AI.Profile.Inspector.Domain.Entities.NormRevision", "Revision")
                        .WithMany()
                        .HasForeignKey("NormRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chunk_revision_link_norm_revisions_norm_revision_id");

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("ISC.AI.Profile.Inspector.Domain.Entities.Division", b =>
                {
                    b.HasOne("ISC.AI.Profile.Inspector.Domain.Entities.Division", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_division_division_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ISC.AI.Profile.Inspector.Domain.Entities.NormDocumentLink", b =>
                {
                    b.HasOne("ISC.AI.Profile.Inspector.Domain.Entities.LegalNorm", "LegalNorm")
                        .WithMany()
                        .HasForeignKey("LegalNormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_norm_document_link_legal_norm_legal_norm_id");

                    b.Navigation("LegalNorm");
                });

            modelBuilder.Entity("ISC.AI.Profile.Inspector.Domain.Entities.NormRevision", b =>
                {
                    b.HasOne("ISC.AI.Profile.Inspector.Domain.Entities.LegalNorm", "Norm")
                        .WithMany("Revisions")
                        .HasForeignKey("NormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_norm_revision_legal_norm_norm_id");

                    b.Navigation("Norm");
                });

            modelBuilder.Entity("ISC.AI.Profile.Inspector.Domain.Entities.Violation", b =>
                {
                    b.HasOne("ISC.AI.Profile.Inspector.Domain.Entities.ViolationCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_violation_violation_category_category_id");

                    b.HasOne("ISC.AI.Profile.Inspector.Domain.Entities.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_violation_division_division_id");

                    b.Navigation("Category");

                    b.Navigation("Division");
                });

            modelBuilder.Entity("ISC.AI.Profile.Inspector.Domain.Entities.ViolationCategory", b =>
                {
                    b.HasOne("ISC.AI.Profile.Inspector.Domain.Entities.ViolationCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_violation_category_violation_category_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ISC.AI.Profile.Inspector.Domain.Entities.Division", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("ISC.AI.Profile.Inspector.Domain.Entities.LegalNorm", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("ISC.AI.Profile.Inspector.Domain.Entities.ViolationCategory", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
