// <auto-generated />
using System;
using ISC.AI.Profile.Inspector.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ISC.AI.Profile.Inspector.Data.Migrations
{
    [DbContext(typeof(InspectorDbContext))]
    partial class InspectorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inspector")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ISC.AI.Profile.Inspector.Domain.Entities.ChunkRevisionLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChunkId")
                        .HasColumnType("integer")
                        .HasColumnName("chunkId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<int>("NormRevisionId")
                        .HasColumnType("integer")
                        .HasColumnName("normRevisionId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id")
                        .HasName("pK_chunkRevisionLink");

                    b.HasIndex("ChunkId")
                        .HasDatabaseName("ixChunkRevisionLinkChunk");

                    b.HasIndex("NormRevisionId")
                        .HasDatabaseName("iX_chunkRevisionLink_normRevisionId");

                    b.ToTable("chunkRevisionLink", "inspector");
                });

            modelBuilder.Entity("ISC.AI.Profile.Inspector.Domain.Entities.LegalNorm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("identifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id")
                        .HasName("pK_legalNorm");

                    b.HasIndex("Identifier")
                        .HasDatabaseName("ixLegalNormIdentifier");

                    b.ToTable("legalNorm", "inspector");
                });

            modelBuilder.Entity("ISC.AI.Profile.Inspector.Domain.Entities.NormDocumentLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("documentId");

                    b.Property<int>("LegalNormId")
                        .HasColumnType("integer")
                        .HasColumnName("legalNormId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id")
                        .HasName("pK_normDocumentLink");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ixNormDocumentLinkDocument");

                    b.HasIndex("LegalNormId")
                        .HasDatabaseName("iX_normDocumentLink_legalNormId");

                    b.ToTable("normDocumentLink", "inspector");
                });

            modelBuilder.Entity("ISC.AI.Profile.Inspector.Domain.Entities.NormRevision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effectiveDate");

                    b.Property<int>("NormId")
                        .HasColumnType("integer")
                        .HasColumnName("normId");

                    b.Property<DateOnly?>("RepealedDate")
                        .HasColumnType("date")
                        .HasColumnName("repealedDate");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id")
                        .HasName("pK_normRevision");

                    b.HasIndex("NormId", "Status")
                        .HasDatabaseName("ixNormRevisionNormStatus");

                    b.ToTable("normRevision", "inspector");
                });

            modelBuilder.Entity("ISC.AI.Profile.Inspector.Domain.Entities.ChunkRevisionLink", b =>
                {
                    b.HasOne("ISC.AI.Profile.Inspector.Domain.Entities.NormRevision", "Revision")
                        .WithMany()
                        .HasForeignKey("NormRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_chunkRevisionLink_normRevisions_normRevisionId");

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("ISC.AI.Profile.Inspector.Domain.Entities.NormDocumentLink", b =>
                {
                    b.HasOne("ISC.AI.Profile.Inspector.Domain.Entities.LegalNorm", "LegalNorm")
                        .WithMany()
                        .HasForeignKey("LegalNormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_normDocumentLink_legalNorm_legalNormId");

                    b.Navigation("LegalNorm");
                });

            modelBuilder.Entity("ISC.AI.Profile.Inspector.Domain.Entities.NormRevision", b =>
                {
                    b.HasOne("ISC.AI.Profile.Inspector.Domain.Entities.LegalNorm", "Norm")
                        .WithMany("Revisions")
                        .HasForeignKey("NormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_normRevision_legalNorm_normId");

                    b.Navigation("Norm");
                });

            modelBuilder.Entity("ISC.AI.Profile.Inspector.Domain.Entities.LegalNorm", b =>
                {
                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
